services:
  document.hydrator:
    synthetic: true
#  document.operation.factory:
#    synthetic: true
  document.operation.factory.event:
    class: Vainyl\Document\Operation\Decorator\EventDocumentOperationFactoryDecorator
    decorates: document.operation.factory
    decoration_priority: 1000
    arguments: ['@document.operation.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']