services:
  document.operation.factory.event:
    decorates: document.operation.factory
    decoration_priority: 1000
    class: Vainyl\Document\Operation\Decorator\EventDocumentOperationFactoryDecorator
    arguments: ['@document.operation.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']